# استفاده از نسخه سبک پایتون
FROM python:3.11-slim

# تنظیم دایرکتوری کاری
WORKDIR /app

# کپی کردن فایل‌های لازم برای نصب
COPY requirements.txt .

# نصب پیش‌نیازها
RUN pip install --no-cache-dir -r requirements.txt

# کپی کردن تمام فایل‌های پروژه به داخل ایمیج
COPY . .

# تعیین پورت پروژه
ENV PORT=8000
EXPOSE 8000

# دستور اجرای پروژه
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]